name: Python Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip3 install -r requirements-dev.txt; fi
    - name: Linting
      run: |
        pylint main.py
        pycodestyle main.py
