name: Python Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Linting
      run: |
        pip3 install --upgrade pip
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip3 install -r requirements-dev.txt; fi
        pylint main.py
        pycodestyle main.py
